apiVersion: dns.cnrm.cloud.google.com/v1alpha1
kind: DNSRecordSet
metadata:
  name: dnsrecordset-sample-a
spec:
  name: "www.example.com."
  type: "A"
  ttl: 300
  managedZoneRef:
    name: dnsrecordset-dep-a
  rrdatas:
  - "8.8.8.8"