apiVersion: compute.cnrm.cloud.google.com/v1alpha1
kind: ComputeGlobalForwardingRule
metadata:
  labels:
    label-one: "value-one"
  name: computeglobalforwardingrule-sample
spec:
  description: "A global forwarding rule"
  targetRef:
    name: computeglobalforwardingrule-dep
  portRange: "80"
  loadBalancingScheme: "INTERNAL_SELF_MANAGED"
  ipProtocol: "TCP"
  ipVersion: "IPV4"
