apiVersion: compute.cnrm.cloud.google.com/v1alpha3
kind: ComputeSnapshot
metadata:
  name: computesnapshot-sample
  labels:
    label-one: "value-one"
spec:
  description: "ComputeSnapshot Sample"
  zone: us-west1-c
  sourceDiskRef:
    name: computesnapshot-dep
  snapshotEncryptionKey:
    rawKey: a2NjIGlzIGF3ZXNvbWUgeW91IHNob3VsZCB0cnkgaXQ=
  sourceDiskEncryptionKey:
    rawKey: SGVsbG8gZnJvbSBHb29nbGUgQ2xvdWQgUGxhdGZvcm0=