# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeInterconnectAttachment
metadata:
  name: computeinterconnectattachment-sample
spec:
  description: example interconnect attachment description
  interconnect: https://www.googleapis.com/compute/v1/projects/my-project/global/interconnects/my-interconnect
  adminEnabled: true
  bandwidth: BPS_50M
  type: DEDICATED
  candidateSubnets:
    - 169.254.0.0/16
  region: us-west1
  vlanTag8021q: 1024
  routerRef:
    name: computeinterconnectattachment-dep
