apiVersion: compute.cnrm.cloud.google.com/v1alpha1
kind: ComputeURLMap
metadata:
  name: computetargethttpproxy-dep
spec:
  defaultServiceRef:
    name: computeurlmap-dep
    kind: ComputeBackendService