label: Config Connector ComputeTargetHTTPProxy
markdownDescription: Creates yaml for a ComputeTargetHTTPProxy resource
insertText: |
  apiVersion: compute.cnrm.cloud.google.com/v1beta1
  kind: ComputeTargetHTTPProxy
  metadata:
    name: \${1:computetargethttpproxy-name}
  spec:
    description: \${2:A sample proxy}
    urlMapRef:
      name: \${3:computetargethttpproxy-dep}
    location: \${4:global}
