label: Config Connector ComputeTargetSSLProxy
markdownDescription: Creates yaml for a ComputeTargetSSLProxy resource
insertText: |
  apiVersion: compute.cnrm.cloud.google.com/v1beta1
  kind: ComputeTargetSSLProxy
  metadata:
    name: \${1:computetargetsslproxy-name}
  spec:
    description: \${2:A sample SSL proxy configured with a default SSL policy.}
    backendServiceRef:
      name: \${3:computetargetsslproxy-dep}
    sslCertificates:
    - name: \${4:computetargetsslproxy-dep}
    sslPolicyRef:
      name: \${5:computetargetsslproxy-dep}
