label: Config Connector ComputeTargetInstance
markdownDescription: Creates yaml for a ComputeTargetInstance resource
insertText: |
  apiVersion: compute.cnrm.cloud.google.com/v1beta1
  kind: ComputeTargetInstance
  metadata:
    name: \${1:computetargetinstance-name}
  spec:
    description: \${2:Target instance, containing a VM instance which will have no NAT
      applied to it and can be used for protocol forwarding.}
    zone: \${3:us-central1-a}
    instanceRef:
      name: \${4:computetargetinstance-dep}
