label: Config Connector ComputeRouterPeer
markdownDescription: Creates yaml for a ComputeRouterPeer resource
insertText: |
  apiVersion: compute.cnrm.cloud.google.com/v1beta1
  kind: ComputeRouterPeer
  metadata:
    name: \${1:computerouterpeer-name}
  spec:
    region: \${2:us-central1}
    peerIpAddress: \${3:169.254.0.2}
    peerAsn: \${4:65513}
    ipAddress:
      external: \${5:169.254.0.1}
    advertisedRoutePriority: \${6:1}
    routerRef:
      name: \${7:computerouterpeer-dep}
    routerInterfaceRef:
      name: \${8:computerouterpeer-dep}
