label: Config Connector ComputeSharedVPCHostProject
markdownDescription: Creates yaml for a ComputeSharedVPCHostProject resource
insertText: |
  apiVersion: compute.cnrm.cloud.google.com/v1beta1
  kind: ComputeSharedVPCHostProject
  metadata:
    name: \${1:computesharedvpchostproject-name}
