label: Config Connector ComputeTargetGRPCProxy
markdownDescription: Creates yaml for a ComputeTargetGRPCProxy resource
insertText: |
  apiVersion: compute.cnrm.cloud.google.com/v1beta1
  kind: ComputeTargetGRPCProxy
  metadata:
    name: \${1:computetargetgrpcproxy-name}
  spec:
    description: \${2:A target gRPC proxy intended for load balancing gRPC traffic,
      referenced by global forwarding rules. References a URL map which specifies how
      traffic routes to gRPC backend services.}
    urlMapRef:
      name: \${3:computetargetgrpcproxy-dep}
    validateForProxyless: \${4:true}
