label: Config Connector ComputeBackendService
markdownDescription: Creates yaml for a ComputeBackendService resource
insertText: |
  apiVersion: compute.cnrm.cloud.google.com/v1beta1
  kind: ComputeBackendService
  metadata:
    name: \${1:computebackendservice-name}
  spec:
    description: \${2:External backend service with cookie-based session affinity.}
    portName: \${3:cookie-cloud}
    timeoutSec: \${4:30}
    healthChecks:
    - healthCheckRef:
        name: \${5:computebackendservice-dep-externalloadbalancing}
    loadBalancingScheme: \${6:EXTERNAL}
    location: \${7:global}
    protocol: \${8:HTTPS}
    affinityCookieTtlSec: \${9:360}
    connectionDrainingTimeoutSec: \${10:60}
    securityPolicyRef:
      name: \${11:computebackendservice-dep-externalloadbalancing}
    sessionAffinity: \${12:GENERATED_COOKIE}
    customRequestHeaders:
    - '\${13:Trailer: custom-trailer}'
    logConfig:
      enable: \${14:true}
      sampleRate: \${15:0.5}
    backend:
    - balancingMode: \${16:RATE}
      capacityScaler: \${17:1}
      description: \${18:A network endpoint group serving this backend with all its
        available capacity, as calculated by number of simultaneous connections.}
      maxRatePerEndpoint: \${19:10}
      group:
        networkEndpointGroupRef:
          name: \${20:computebackendservice-dep-externalloadbalancing}
