label: Config Connector ComputeFirewallPolicyRule
markdownDescription: Creates yaml for a ComputeFirewallPolicyRule resource
insertText: |
  apiVersion: compute.cnrm.cloud.google.com/v1beta1
  kind: ComputeFirewallPolicyRule
  metadata:
    name: \${1:computefirewallpolicyrule-name}
  spec:
    action: \${2:deny}
    description: \${3:A Firewall Policy Rule}
    direction: \${4:INGRESS}
    disabled: \${5:false}
    enableLogging: \${6:false}
    firewallPolicyRef:
      name: \${7:firewallpolicyrule-dep}
    match:
      layer4Configs:
      - ipProtocol: \${8:tcp}
      srcIPRanges:
      - \${9:10.100.0.1/32}
    priority: \${10:9000}
    targetResources:
    - name: \${11:firewallpolicyrule-dep}
    targetServiceAccounts:
    - name: \${12:firewallpolicyrule-dep}
