label: Config Connector ComputeHTTPHealthCheck
markdownDescription: Creates yaml for a ComputeHTTPHealthCheck resource
insertText: |
  apiVersion: compute.cnrm.cloud.google.com/v1beta1
  kind: ComputeHTTPHealthCheck
  metadata:
    name: \${1:computehttphealthcheck-name}
  spec:
    checkIntervalSec: \${2:10}
    description: \${3:example HTTP health check}
    healthyThreshold: \${4:2}
    port: \${5:80}
    requestPath: \${6:/}
    timeoutSec: \${7:5}
    unhealthyThreshold: \${8:2}
