label: Config Connector ComputeSecurityPolicy
markdownDescription: Creates yaml for a ComputeSecurityPolicy resource
insertText: |
  apiVersion: compute.cnrm.cloud.google.com/v1beta1
  kind: ComputeSecurityPolicy
  metadata:
    name: \${1:computesecuritypolicy-name}
  spec:
    description: \${2:A generally permissive policy that locks out a large block of
      untrusted IPs, except for some allowed trusted IP ranges within them, and never
      allows IPs from a denylist.}
    rule:
    - action: \${3:allow}
      priority: \${4:2147483647}
      match:
        versionedExpr: \${5:SRC_IPS_V1}
        config:
          srcIpRanges:
          - \${6:*}
      description: \${7:This rule must be included in any rule array. Action can change.}
    - action: \${8:deny(502)}
      priority: \${9:111111111}
      match:
        versionedExpr: \${10:SRC_IPS_V1}
        config:
          srcIpRanges:
          - \${11:60.0.0.0/6}
      description: \${12:Untrusted range. Block IPs and return 502.}
    - action: \${13:allow}
      priority: \${14:555}
      match:
        versionedExpr: \${15:SRC_IPS_V1}
        config:
          srcIpRanges:
          - \${16:63.0.0.0/8}
          - \${17:61.128.0.0/10}
      description: \${18:Even though they're in an untrusted block, these ranges are
        OK.}
    - action: \${19:deny(403)}
      priority: \${20:0}
      match:
        versionedExpr: \${21:SRC_IPS_V1}
        config:
          srcIpRanges:
          - \${22:145.4.56.4/30}
          - \${23:63.63.63.63/32}
          - \${24:4.5.4.0/24}
      description: \${25:Never allow these denylisted IP ranges.}
