label: Config Connector ConfigControllerInstance
markdownDescription: Creates yaml for a ConfigControllerInstance resource
insertText: |
  apiVersion: configcontroller.cnrm.cloud.google.com/v1beta1
  kind: ConfigControllerInstance
  metadata:
    labels:
      \${1:label-one}: \${2:value-one}
    name: \${3:configcontrollerinstance-name}
  spec:
    projectRef:
      external: \${4:projects/[PROJECT_ID?]}
    location: \${5:us-central1}
    managementConfig:
      fullManagementConfig:
        clusterCidrBlock: \${6:/20}
        servicesCidrBlock: \${7:/24}
