label: Config Connector ContainerAnalysisNote
markdownDescription: Creates yaml for a ContainerAnalysisNote resource
insertText: |
  apiVersion: containeranalysis.cnrm.cloud.google.com/v1beta1
  kind: ContainerAnalysisNote
  metadata:
    name: \${1:containeranalysisnote-name}
  spec:
    shortDescription: \${2:short description}
    longDescription: \${3:long description}
    relatedUrl:
    - url: \${4:some.url}
      label: \${5:test}
    - url: \${6:google.com}
      label: \${7:google}
    attestation:
      hint:
        humanReadableName: \${8:Attestor Note}
