label: Config Connector DLPStoredInfoType
markdownDescription: Creates yaml for a DLPStoredInfoType resource
insertText: |
  apiVersion: dlp.cnrm.cloud.google.com/v1beta1
  kind: DLPStoredInfoType
  metadata:
    name: \${1:dlpstoredinfotype-name}
  spec:
    projectRef:
      external: \${2:projects/[PROJECT_ID?]}
    location: \${3:us-west2}
    largeCustomDictionary:
      outputPath:
        path: \${4:gs://[DLP_TEST_BUCKET?]/large-custom-dictionary-2}
      bigQueryField:
        table:
          projectRef:
            external: \${5:projects/[PROJECT_ID?]}
          datasetRef:
            name: \${6:dlpstoredinfotypedepbigqueryfieldstoredinfotype}
          tableRef:
            name: \${7:dlpstoredinfotypedepbigqueryfieldstoredinfotype}
        field:
          name: \${8:sample_field}
