label: Config Connector DNSPolicy
markdownDescription: Creates yaml for a DNSPolicy resource
insertText: |
  apiVersion: dns.cnrm.cloud.google.com/v1beta1
  kind: DNSPolicy
  metadata:
    name: \${1:dnspolicy-name}
  spec:
    alternativeNameServerConfig:
      targetNameServers:
      - ipv4Address: \${2:104.132.166.92}
    description: \${3:Example DNS policy}
    enableInboundForwarding: \${4:true}
    enableLogging: \${5:true}
    networks:
    - networkRef:
        name: \${6:dnspolicy-dep}
