label: Config Connector FilestoreInstance
markdownDescription: Creates yaml for a FilestoreInstance resource
insertText: |
  apiVersion: filestore.cnrm.cloud.google.com/v1beta1
  kind: FilestoreInstance
  metadata:
    name: \${1:filestoreinstance-name}
  spec:
    projectRef:
      external: \${2:projects/[PROJECT_ID?]}
    description: \${3:A sample filestore instance}
    fileShares:
    - capacityGb: \${4:4800}
      name: \${5:my_share}
      nfsExportOptions:
      - accessMode: \${6:READ_WRITE}
        anonGid: \${7:65534}
        anonUid: \${8:65534}
        ipRanges:
        - \${9:172.217.14.238}
        squashMode: \${10:ROOT_SQUASH}
    location: \${11:us-central1-c}
    networks:
    - networkRef:
        name: \${12:filestoreinstance-dep}
      modes:
      - \${13:MODE_IPV4}
      reservedIPRange: \${14:10.0.0.0/29}
    tier: \${15:PREMIUM}
