label: Config Connector IAMWorkloadIdentityPoolProvider
markdownDescription: Creates yaml for a IAMWorkloadIdentityPoolProvider resource
insertText: |
  apiVersion: iam.cnrm.cloud.google.com/v1beta1
  kind: IAMWorkloadIdentityPoolProvider
  metadata:
    name: \${1:iamworkloadidentitypoolprovider-name}
  spec:
    projectRef:
      external: \${2:projects/[PROJECT_ID?]}
    location: \${3:global}
    workloadIdentityPoolRef:
      name: \${4:iamwipp-dep-oidc}
    attributeMapping:
      google.subject: \${5:true}
    oidc:
      issuerUri: \${6:https://example.com/}
      allowedAudiences:
      - \${7:sample-audience}
