label: Config Connector IAMServiceAccountKey
markdownDescription: Creates yaml for a IAMServiceAccountKey resource
insertText: |
  apiVersion: iam.cnrm.cloud.google.com/v1beta1
  kind: IAMServiceAccountKey
  metadata:
    labels:
      \${1:label-one}: \${2:value-one}
    name: \${3:iamserviceaccountkey-name}
  spec:
    publicKeyType: \${4:TYPE_X509_PEM_FILE}
    keyAlgorithm: \${5:KEY_ALG_RSA_2048}
    privateKeyType: \${6:TYPE_GOOGLE_CREDENTIALS_FILE}
    serviceAccountRef:
      name: \${7:iamserviceaccountkey-dep}
