label: Config Connector IAMServiceAccount
markdownDescription: Creates yaml for a IAMServiceAccount resource
insertText: |
  apiVersion: iam.cnrm.cloud.google.com/v1beta1
  kind: IAMServiceAccount
  metadata:
    labels:
      \${1:label-one}: \${2:value-one}
    name: \${3:iamserviceaccount-name}
  spec:
    displayName: \${4:Example Service Account}
