label: Config Connector IAMAuditConfig
markdownDescription: Creates yaml for a IAMAuditConfig resource
insertText: |
  apiVersion: iam.cnrm.cloud.google.com/v1beta1
  kind: IAMAuditConfig
  metadata:
    name: \${1:iamauditconfig-name}
  spec:
    service: \${2:allServices}
    auditLogConfigs:
    - logType: \${3:DATA_WRITE}
    - logType: \${4:DATA_READ}
      exemptedMembers:
      - \${5:serviceAccount:iamauditconfig-dep-projlevel@[PROJECT_ID?].iam.gserviceaccount.com}
    resourceRef:
      kind: \${6:Project}
      external: \${7:projects/[PROJECT_ID?]}
