label: Config Connector IdentityPlatformOAuthIDPConfig
markdownDescription: Creates yaml for a IdentityPlatformOAuthIDPConfig resource
insertText: |
  apiVersion: identityplatform.cnrm.cloud.google.com/v1beta1
  kind: IdentityPlatformOAuthIDPConfig
  metadata:
    name: \${1:identityplatformoauthidpconfig-name}
  spec:
    resourceID: \${2:oidc.project-oauth-idp-config-sample}
    displayName: \${3:sample oauth idp config}
    clientId: \${4:client-id}
    issuer: \${5:issuer}
    enabled: \${6:true}
    clientSecret:
      valueFrom:
        secretKeyRef:
          key: \${7:clientSecret}
          name: \${8:identityplatformoauthidpconfig-dep}
