label: Config Connector IdentityPlatformTenant
markdownDescription: Creates yaml for a IdentityPlatformTenant resource
insertText: |
  apiVersion: identityplatform.cnrm.cloud.google.com/v1beta1
  kind: IdentityPlatformTenant
  metadata:
    name: \${1:identityplatformtenant-name}
  spec:
    displayName: \${2:sample-tenant}
    allowPasswordSignup: \${3:true}
    enableAnonymousUser: \${4:false}
    mfaConfig:
      state: \${5:ENABLED}
    testPhoneNumbers:
      "+12345678901": \${6:123451}
      "+16505550000": \${7:123450}
