label: Config Connector LoggingLogBucket
markdownDescription: Creates yaml for a LoggingLogBucket resource
insertText: |
  apiVersion: logging.cnrm.cloud.google.com/v1beta1
  kind: LoggingLogBucket
  metadata:
    name: \${1:logginglogbucket-name}
  spec:
    projectRef:
      external: \${2:projects/[PROJECT_ID?]}
    location: \${3:global}
    description: \${4:A sample log bucket}
    locked: \${5:false}
    retentionDays: \${6:30}
