label: Config Connector PrivateCACertificate
markdownDescription: Creates yaml for a PrivateCACertificate resource
insertText: |
  apiVersion: privateca.cnrm.cloud.google.com/v1beta1
  kind: PrivateCACertificate
  metadata:
    labels:
      \${1:key}: \${2:value}
    name: \${3:privatecacertificate-name}
  spec:
    location: \${4:us-central1}
    certificateAuthorityRef:
      name: \${5:privatecacertificate-dep-basic}
    caPoolRef:
      name: \${6:privatecacertificate-dep-basic}
    lifetime: \${7:860s}
    subjectMode: \${8:DEFAULT}
    config:
      subjectConfig:
        subject:
          commonName: \${9:san1.example.com}
        subjectAltName:
          dnsNames:
          - \${10:san1.example.com}
          uris:
          - \${11:http://www.ietf.org/rfc/rfc3986.txt}
          emailAddresses:
          - \${12:test_example@google.com}
          ipAddresses:
          - \${13:127.0.0.1}
      x509Config:
        caOptions:
          isCa: \${14:false}
        keyUsage:
          baseKeyUsage:
            crlSign: \${15:true}
          extendedKeyUsage:
            serverAuth: \${16:true}
      publicKey:
        format: \${17:PEM}
        key: \${18:LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUlJQ0lqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FnOEFNSUlDQ2dLQ0FnRUF2NndlQzFhVDE2bDJxUzZxZFljeQo3Qk9qelA3VHdUOXpVQWlGaFdwTDI1NkdScUM4eVFSZHFNc2k2OFEvLzc2MklVeXUvcWFIYkVnUThXUm1RZFZWCkdEbHhrQmZyQS9pWEIyZGd1anE4amgwSFdJVjJldjNUZXJWM2FVd3ZZVWxyb3docTAyN1NYOVUxaGJ1ZmRHQ00KdUtzSGlGMDVFcmdOdkV1UjhYQWtlSi9ZVjJEVjIrc1JxK1dnOXk0UndVWWJkY2hkRnR5MWQ1U1gvczBZcXN3Zwp5T0c5Vm9DZFI3YmFGMjJ1Z2hWUjQ0YVJtKzgzbWd0cUFaNE0rUnBlN0pHUnNVR1kvcFIzOTFUb2kwczhFbjE1CkpHaUFocVgyVzBVby9GWlpyeTN5dXFSZmRIWUVOQitBRHV5VE1UclVhS1p2N2V1YTBsVEJ6NW9vbTNqU0YzZ3YKSTdTUW9MZEsvamhFVk9PcTQxSWpCOEQ2MFNnZDY5YkQ3eVRJNTE2eXZaL3MzQXlLelc2ZjZLbmpkYkNjWktLVAowR0FlUE5MTmhEWWZTbEE5YndKOEhRUzJGZW5TcFNUQXJLdkdpVnJzaW5KdU5qYlFkUHVRSGNwV2Y5eDFtM0dSClRNdkYrVE5ZTS9scDdJTDJWTWJKUmZXUHkxaVd4bTlGMVlyNmRrSFZvTFA3b2NZa05SSG9QTHV0NUU2SUZKdEsKbFZJMk5uZVVZSkduWVNPKzF4UFY5VHFsSmVNTndyM3VGTUFOOE4vb0IzZjRXV3d1UllnUjBMNWcyQStMdngrZwpiYmRsK1RiLzBDTmZzbGZTdURyRlY4WjRuNmdWd2I5WlBHbE5IQ3ZucVJmTFVwUkZKd21SN1VZdnppL0U3clhKCkVEa0srdGNuUGt6Mkp0amRMS1I3cVZjQ0F3RUFBUT09Ci0tLS0tRU5EIFBVQkxJQyBLRVktLS0tLQ==}
    projectRef:
      external: \${19:projects/[PROJECT_ID?]}
