label: Config Connector PubSubTopic
markdownDescription: Creates yaml for a PubSubTopic resource
insertText: |
  apiVersion: pubsub.cnrm.cloud.google.com/v1beta1
  kind: PubSubTopic
  metadata:
    labels:
      \${1:label-one}: \${2:value-one}
    name: \${3:pubsubtopic-name}
  spec:
    schemaSettings:
      schemaRef:
        name: \${4:pubsubtopic-dep}
      encoding: \${5:JSON}
