label: Config Connector RecaptchaEnterpriseKey
markdownDescription: Creates yaml for a RecaptchaEnterpriseKey resource
insertText: |
  apiVersion: recaptchaenterprise.cnrm.cloud.google.com/v1beta1
  kind: RecaptchaEnterpriseKey
  metadata:
    labels:
      \${1:label-one}: \${2:value-one}
    name: \${3:recaptchaenterprisekey-name}
  spec:
    projectRef:
      external: \${4:projects/[PROJECT_ID?]}
    displayName: \${5:display-name-one}
    webSettings:
      allowAllDomains: \${6:true}
      integrationType: \${7:CHECKBOX}
      challengeSecurityPreference: \${8:USABILITY}
    testingOptions:
      testingScore: \${9:0.5}
      testingChallenge: \${10:NOCAPTCHA}
