label: Config Connector SecretManagerSecretVersion
markdownDescription: Creates yaml for a SecretManagerSecretVersion resource
insertText: |
  apiVersion: secretmanager.cnrm.cloud.google.com/v1beta1
  kind: SecretManagerSecretVersion
  metadata:
    name: \${1:secretmanagersecretversion-name}
  spec:
    enabled: \${2:true}
    secretData:
      valueFrom:
        secretKeyRef:
          key: \${3:secretData}
          name: \${4:secretmanagersecretversion-dep}
    secretRef:
      name: \${5:secretmanagersecretversion-dep}
