label: Config Connector SecretManagerSecret
markdownDescription: Creates yaml for a SecretManagerSecret resource
insertText: |
  apiVersion: secretmanager.cnrm.cloud.google.com/v1beta1
  kind: SecretManagerSecret
  metadata:
    labels:
      \${1:replication-type}: \${2:automatic}
    name: \${3:secretmanagersecret-name}
  spec:
    replication:
      automatic: \${4:true}
