label: Config Connector SQLUser
markdownDescription: Creates yaml for a SQLUser resource
insertText: |
  apiVersion: sql.cnrm.cloud.google.com/v1beta1
  kind: SQLUser
  metadata:
    name: \${1:sqluser-name}
  spec:
    instanceRef:
      name: \${2:sqluser-dep}
    host: \${3:%}
    password:
      valueFrom:
        secretKeyRef:
          name: \${4:sqluser-dep}
          key: \${5:password}
