label: Config Connector StorageBucketAccessControl
markdownDescription: Creates yaml for a StorageBucketAccessControl resource
insertText: |
  apiVersion: storage.cnrm.cloud.google.com/v1beta1
  kind: StorageBucketAccessControl
  metadata:
    labels:
      \${1:label-one}: \${2:value-one}
    name: \${3:storagebucketaccesscontrol-name}
  spec:
    bucketRef:
      name: \${4:[PROJECT_ID?]-bucketaccesscontrol-dep}
    entity: \${5:allAuthenticatedUsers}
    role: \${6:READER}
