label: Config Connector StorageTransferJob
markdownDescription: Creates yaml for a StorageTransferJob resource
insertText: |
  apiVersion: storagetransfer.cnrm.cloud.google.com/v1beta1
  kind: StorageTransferJob
  metadata:
    name: \${1:storagetransferjob-name}
  spec:
    description: \${2:Sample storage transfer job}
    schedule:
      startTimeOfDay:
        seconds: \${3:0}
        hours: \${4:0}
        minutes: \${5:0}
        nanos: \${6:0}
      scheduleEndDate:
        day: \${7:31}
        month: \${8:12}
        year: \${9:9999}
      scheduleStartDate:
        day: \${10:28}
        month: \${11:1}
        year: \${12:2020}
    status: \${13:ENABLED}
    transferSpec:
      gcsDataSink:
        bucketRef:
          name: \${14:[PROJECT_ID?]-storagetransferjob-dep1}
      gcsDataSource:
        bucketRef:
          name: \${15:[PROJECT_ID?]-storagetransferjob-dep2}
      objectConditions:
        maxTimeElapsedSinceLastModification: \${16:5s}
        minTimeElapsedSinceLastModification: \${17:2s}
      transferOptions:
        deleteObjectsUniqueInSink: \${18:false}
        overwriteObjectsAlreadyExistingInSink: \${19:true}
