# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: core.cnrm.cloud.google.com/v1alpha1
kind: ServiceMapping
metadata:
  name: servicenetworking.cnrm.cloud.google.com
  namespace: cnrm-system
spec:
  name: ServiceNetworking
  version: v1beta1
  serviceHostName: "servicenetworking.googleapis.com"
  resources:
    - name: google_service_networking_connection
      kind: ServiceNetworkingConnection
      idTemplate: "projects/{{project}}/global/networks/{{network}}:{{service}}"
      # doesn't have an individual URL, returned as a list for a network name parameter
      idTemplateCanBeUsedToMatchResourceName: false
      resourceAvailableInAssetInventory: false
      resourceReferences:
      - tfField: network
        key: networkRef
        gvk:
          kind: ComputeNetwork
          version: v1beta1
          group: compute.cnrm.cloud.google.com
      - tfField: reserved_peering_ranges
        gvk:
          kind: ComputeAddress
          version: v1beta1
          group: compute.cnrm.cloud.google.com
      containers:
      - type: project
        tfField: project
