# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: core.cnrm.cloud.google.com/v1alpha1
kind: ServiceMapping
metadata:
  name: sourcerepo.cnrm.cloud.google.com
  namespace: cnrm-system
spec:
  name: SourceRepo
  version: v1beta1
  serviceHostName: "sourcerepo.googleapis.com"
  resources:
    - name: google_sourcerepo_repository
      kind: SourceRepoRepository
      metadataMapping:
        name: name
      resourceID:
        targetField: name
      idTemplate: "projects/{{project}}/repos/{{name}}"
      idTemplateCanBeUsedToMatchResourceName: true
      resourceAvailableInAssetInventory: true
      containers:
        - type: project
          tfField: project
      iamConfig:
        policyName: google_sourcerepo_repository_iam_policy
        policyMemberName: google_sourcerepo_repository_iam_member
        referenceField:
          name: repository
          type: id
      resourceReferences:
        - tfField: pubsub_configs.topic
          key: topicRef
          gvk:
            kind: PubSubTopic
            version: v1beta1
            group: pubsub.cnrm.cloud.google.com
        - tfField: pubsub_configs.service_account_email
          description: |-
            Service account used for publishing Cloud Pub/Sub messages. This
            service account needs to be in the same project as the
            pubsubConfig. When added, the caller needs to have
            iam.serviceAccounts.actAs permission on this service account. If
            unspecified, it defaults to the compute engine default service
            account.
          key: serviceAccountRef
          gvk:
            kind: IAMServiceAccount
            version: v1beta1
            group: iam.cnrm.cloud.google.com
          targetField: email
