apiVersion: compute.cnrm.cloud.google.com/v1alpha3
kind: ComputeHealthCheck
metadata:
  name: computeglobalforwardingrule-dep
spec:
  checkIntervalSec: 10
  httpHealthCheck:
    port: 80
  location: global