# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: monitoring.cnrm.cloud.google.com/v1beta1
kind: MonitoringUptimeCheckConfig
metadata:
  name: monitoringuptimecheckconfig-sample
spec:
  projectRef:
    # Replace ${PROJECT_ID?} with your project ID.
    external: projects/${PROJECT_ID?}
  displayName: "A sample http uptime check config"
  period: 60s
  timeout: 30s
  contentMatchers:
    - content: ".*"
      matcher: "MATCHES_REGEX"
  selectedRegions:
    - USA
  monitoredResource:
    type: "uptime_url"
    filterLabels:
      host: "192.168.1.1"
      # Replace ${PROJECT_ID?} with the ID of a monitored project.
      project_id: ${PROJECT_ID?}
  httpCheck:
    requestMethod: POST
    useSsl: true
    path: "/main"
    port: 80
    authInfo:
      username: test
      password:
        valueFrom:
          secretKeyRef:
            name: monitoringuptimecheckconfig-dep
            key: password
    maskHeaders: true
    headers:
      header-one: "value-one"
    contentType: "URL_ENCODED"
    validateSsl: false
    body: "c3RyaW5nCg=="
