apiVersion: compute.cnrm.cloud.google.com/v1alpha3
kind: ComputeRouterNAT
metadata:
  name: computerouternat-sample
spec:
  region: us-west1
  natIpAllocateOption: AUTO_ONLY
  routerRef:
    name: computerouternat-dep
  sourceSubnetworkIpRangesToNat: LIST_OF_SUBNETWORKS
  subnetwork:
  - subnetworkRef:
      name: computerouternat-dep
    sourceIpRangesToNat:
    - ALL_IP_RANGES
