# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: monitoring.cnrm.cloud.google.com/v1beta1
kind: MonitoringNotificationChannel
metadata:
  # The metadata.labels field doesn't configure the notification channel
  # Specify notification channel configuration in spec.labels
  labels:
    response-priority: longterm
    target-user: dev
  name: monitoringnotificationchannel-sample-disabled-email
spec:
  type: email
  # The spec.labels field below is for configuring the desired behaviour of the notification channel
  # It does not apply labels to the resource in the cluster
  labels:
    email_address: dev@example.com
  description: A disabled channel that would send notifications via email if enabled.
  enabled: false
