apiVersion: compute.cnrm.cloud.google.com/v1alpha3
kind: ComputeVPNTunnel
metadata:
  name: computevpntunnel-example
  labels:
    foo: bar
spec:
  peerIp: "15.0.0.120"
  region: us-central1
  sharedSecret: "a secret message"
  targetVPNGatewayRef:
    name: computevpntunnel-dep
  localTrafficSelector:
   - "192.168.0.0/16"