apiVersion: v1
kind: ServiceAccount
metadata:
  name: iampolicy-ksa-dep
  annotations:
    # replace ${PROJECT_ID?} with your project name
    iam.gke.io/gcp-service-account: iampolicy-gsa-dep@${PROJECT_ID?}.iam.gserviceaccount.com
