apiVersion: storage.cnrm.cloud.google.com/v1beta1
kind: StorageBucket
metadata:
  annotations:
    cnrm.cloud.google.com/force-destroy: "true"
  # You MUST change the name to a globally unique bucket name.
  name: dataflowjob-dep-streaming
