# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: foos.test.cnrm.cloud.google.com
  labels:
    cnrm.cloud.google.com/system: "true"
    cnrm.cloud.google.com/managed-by-kcc: "true"
spec:
  scope: Namespaced
  group: test.cnrm.cloud.google.com
  names:
    kind: foo
    plural: foos
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        type: object
    served: true
    storage: true
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: bars.test.cnrm.cloud.google.com
  labels:
    cnrm.cloud.google.com/system: "true"
    cnrm.cloud.google.com/managed-by-kcc: "true"
spec:
  scope: Namespaced
  group: test.cnrm.cloud.google.com
  names:
    kind: bar
    plural: bars
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        type: object
    served: true
    storage: true
