apiVersion: compute.cnrm.cloud.google.com/v1alpha1
kind: ComputeAddress
metadata:
  name: computeaddress-sample
spec:
  addressType: INTERNAL
  description: a test address
  region: us-central1
  networkTier: STANDARD
  subnetworkRef:
    name: computeaddress-dep