apiVersion: sql.cnrm.cloud.google.com/v1alpha3
kind: SQLUser
metadata:
  name: sqluser-sample
spec:
  instanceRef:
    name: mysql-instance-sample-with-sql-user
  host: "%"
  password: change-me
# after running this sample, you can verify that sql instance can be accessed
# with user credentials by running from cloud shell:
# gcloud sql connect mysql-instance-sample-with-sql-user --user=sqluser-sample