apiVersion: spanner.cnrm.cloud.google.com/v1alpha2
kind: SpannerDatabase
metadata:
  name: spannerdatabase-sample
spec:
  instanceRef:
    name: spannerdatabase-dep
  ddl:
  - "CREATE TABLE t1 (t1 INT64 NOT NULL,) PRIMARY KEY(t1)"