apiVersion: compute.cnrm.cloud.google.com/v1alpha3
kind: ComputeURLMap
metadata:
  name: computeurlmap-sample
spec:
  defaultService:
    backendServiceRef:
      name: computeurlmap-dep
  location: global
