apiVersion: firestore.cnrm.cloud.google.com/v1alpha1
kind: FirestoreIndex
metadata:
  name: firestoreindex-sample
spec:
  collection: sample-collection
  fields:
  - fieldPath: field1
    order: ASCENDING
  - fieldPath: field2
    order: DESCENDING
  queryScope: COLLECTION
