apiVersion: storage.cnrm.cloud.google.com/v1alpha2
kind: StorageDefaultObjectAccessControl
metadata:
  labels:
    label-one: "value-one"
  name: storagedefaultobjectaccesscontrol-sample
spec:
  bucketRef:
    name: storagedefaultobjectaccesscontrol
  entity: allAuthenticatedUsers
  role: READER
