apiVersion: iam.cnrm.cloud.google.com/v1alpha1
kind: IAMPolicy
metadata:
  name: cnrm-bookstore-spanner-policy
spec:
  resourceRef:
    apiVersion: spanner.cnrm.cloud.google.com/v1alpha2
    kind: SpannerInstance
    name: cnrm-instance
  bindings:
    - role: roles/editor
      members:
        - serviceAccount:cnrm-bookstore-inventory@[PROJECT_ID].iam.gserviceaccount.com