# Copyright 2024 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: compositions

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - "experiments/compositions/**"
  push:
    branches: ["master"]
    paths:
      - "experiments/compositions/**"

env:
  GOWORK: off
jobs:
  verify-goimports:
    runs-on: ubuntu-latest
    steps:
      - name: Set up go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          stable: true
      - uses: actions/checkout@v4
      - name: verify goimports
        run: |
          ./experiments/compositions/scripts/github-actions/verify-goimports.sh
  verify-gomod:
    runs-on: ubuntu-latest
    steps:
      - name: Set up go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          stable: true
      - uses: actions/checkout@v4
      - run: |
          ./experiments/compositions/scripts/github-actions/format-gomod.sh
      - run: |
          changes=$(git status --porcelain)
          if [[ -n "${changes}" ]]; then
            echo "::error Changes detected from dev/format-gomod:"
            echo "::error (You may need to run go clean -cache -modcache)"
            git diff | head -n60
            echo "${changes}"
            exit 1
          fi
  test-expander-helm:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
      - name: "verify expander-helm in a kind cluster"
        run: |
          ./experiments/compositions/scripts/github-actions/helm-test.sh
  test-expander-getter:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
      - name: "verify expander-getter in a kind cluster"
        run: |
          ./experiments/compositions/scripts/github-actions/getter-test.sh
  test-expander-jinja2:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
      - name: "verify expander-jinja2 in a kind cluster"
        run: |
          ./experiments/compositions/scripts/github-actions/jinja2-test.sh
  e2e-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - name: "run e2e tests"
        run: |
          ./experiments/compositions/scripts/github-actions/e2e-test.sh
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true
